export interface AppCurrency {
    code: string;
    nameKey: string;
    flag: string;
}

export const SUPPORTED_CURRENCIES: AppCurrency[] = [
    { code: 'PLN', nameKey: 'currencies.pln', flag: '🇵🇱' },
    { code: 'USD', nameKey: 'currencies.usd', flag: '🇺🇸' },
    { code: 'EUR', nameKey: 'currencies.eur', flag: '🇪🇺' },
    { code: 'CHF', nameKey: 'currencies.chf', flag: '🇨🇭' },
    { code: 'GBP', nameKey: 'currencies.gbp', flag: '🇬🇧' },
    { code: 'JPY', nameKey: 'currencies.jpy', flag: '🇯🇵' },
    { code: 'CZK', nameKey: 'currencies.czk', flag: '🇨🇿' },
    { code: 'AUD', nameKey: 'currencies.aud', flag: '🇦🇺' },
    { code: 'CAD', nameKey: 'currencies.cad', flag: '🇨🇦' },
    { code: 'DKK', nameKey: 'currencies.dkk', flag: '🇩🇰' },
    { code: 'HUF', nameKey: 'currencies.huf', flag: '🇭🇺' },
    { code: 'NOK', nameKey: 'currencies.nok', flag: '🇳🇴' },
    { code: 'SEK', nameKey: 'currencies.sek', flag: '🇸🇪' },
    { code: 'UAH', nameKey: 'currencies.uah', flag: '🇺🇦' },
    { code: 'THB', nameKey: 'currencies.thb', flag: '🇹🇭' },
    { code: 'HKD', nameKey: 'currencies.hkd', flag: '🇭🇰' },
    { code: 'NZD', nameKey: 'currencies.nzd', flag: '🇳🇿' },
    { code: 'SGD', nameKey: 'currencies.sgd', flag: '🇸🇬' },
    { code: 'ISK', nameKey: 'currencies.isk', flag: '🇮🇸' },
    { code: 'RON', nameKey: 'currencies.ron', flag: '🇷🇴' },
    { code: 'BGN', nameKey: 'currencies.bgn', flag: '🇧🇬' },
    { code: 'TRY', nameKey: 'currencies.try', flag: '🇹🇷' },
    { code: 'ILS', nameKey: 'currencies.ils', flag: '🇮🇱' },
    { code: 'CLP', nameKey: 'currencies.clp', flag: '🇨🇱' },
    { code: 'PHP', nameKey: 'currencies.php', flag: '🇵🇭' },
    { code: 'MXN', nameKey: 'currencies.mxn', flag: '🇲🇽' },
    { code: 'ZAR', nameKey: 'currencies.zar', flag: '🇿🇦' },
    { code: 'BRL', nameKey: 'currencies.brl', flag: '🇧🇷' },
    { code: 'MYR', nameKey: 'currencies.myr', flag: '🇲🇾' },
    { code: 'IDR', nameKey: 'currencies.idr', flag: '🇮🇩' },
    { code: 'INR', nameKey: 'currencies.inr', flag: '🇮🇳' },
    { code: 'KRW', nameKey: 'currencies.krw', flag: '🇰🇷' },
    { code: 'CNY', nameKey: 'currencies.cny', flag: '🇨🇳' },
    { code: 'XDR', nameKey: 'currencies.xdr', flag: '🌐' },
    { code: 'AFN', nameKey: 'currencies.afn', flag: '🇦🇫' },
    { code: 'MGA', nameKey: 'currencies.mga', flag: '🇲🇬' },
    { code: 'PAB', nameKey: 'currencies.pab', flag: '🇵🇦' },
    { code: 'ETB', nameKey: 'currencies.etb', flag: '🇪🇹' },
    { code: 'VES', nameKey: 'currencies.ves', flag: '🇻🇪' },
    { code: 'BOB', nameKey: 'currencies.bob', flag: '🇧🇴' },
    { code: 'CRC', nameKey: 'currencies.crc', flag: '🇨🇷' },
    { code: 'SVC', nameKey: 'currencies.svc', flag: '🇸🇻' },
    { code: 'NIO', nameKey: 'currencies.nio', flag: '🇳🇮' },
    { code: 'GMD', nameKey: 'currencies.gmd', flag: '🇬🇲' },
    { code: 'MKD', nameKey: 'currencies.mkd', flag: '🇲🇰' },
    { code: 'DZD', nameKey: 'currencies.dzd', flag: '🇩🇿' },
    { code: 'BHD', nameKey: 'currencies.bhd', flag: '🇧🇭' },
    { code: 'IQD', nameKey: 'currencies.iqd', flag: '🇮🇶' },
    { code: 'JOD', nameKey: 'currencies.jod', flag: '🇯🇴' },
    { code: 'KWD', nameKey: 'currencies.kwd', flag: '🇰🇼' },
    { code: 'LYD', nameKey: 'currencies.lyd', flag: '🇱🇾' },
    { code: 'RSD', nameKey: 'currencies.rsd', flag: '🇷🇸' },
    { code: 'TND', nameKey: 'currencies.tnd', flag: '🇹🇳' },
    { code: 'MAD', nameKey: 'currencies.mad', flag: '🇲🇦' },
    { code: 'AED', nameKey: 'currencies.aed', flag: '🇦🇪' },
    { code: 'STN', nameKey: 'currencies.stn', flag: '🇸🇹' },
    { code: 'BSD', nameKey: 'currencies.bsd', flag: '🇧🇸' },
    { code: 'BBD', nameKey: 'currencies.bbd', flag: '🇧🇧' },
    { code: 'BZD', nameKey: 'currencies.bzd', flag: '🇧🇿' },
    { code: 'BND', nameKey: 'currencies.bnd', flag: '🇧🇳' },
    { code: 'FJD', nameKey: 'currencies.fjd', flag: '🇫🇯' },
    { code: 'GYD', nameKey: 'currencies.gyd', flag: '🇬🇾' },
    { code: 'JMD', nameKey: 'currencies.jmd', flag: '🇯🇲' },
    { code: 'LRD', nameKey: 'currencies.lrd', flag: '🇱🇷' },
    { code: 'NAD', nameKey: 'currencies.nad', flag: '🇳🇦' },
    { code: 'SRD', nameKey: 'currencies.srd', flag: '🇸🇷' },
    { code: 'TTD', nameKey: 'currencies.ttd', flag: '🇹🇹' },
    { code: 'XCD', nameKey: 'currencies.xcd', flag: '🇦🇬' },
    { code: 'SBD', nameKey: 'currencies.sbd', flag: '🇸🇧' },
    { code: 'VND', nameKey: 'currencies.vnd', flag: '🇻🇳' },
    { code: 'AMD', nameKey: 'currencies.amd', flag: '🇦🇲' },
    { code: 'CVE', nameKey: 'currencies.cve', flag: '🇨🇻' },
    { code: 'AWG', nameKey: 'currencies.awg', flag: '🇦🇼' },
    { code: 'BIF', nameKey: 'currencies.bif', flag: '🇧🇮' },
    { code: 'XOF', nameKey: 'currencies.xof', flag: '🌐' },
    { code: 'XAF', nameKey: 'currencies.xaf', flag: '🌐' },
    { code: 'XPF', nameKey: 'currencies.xpf', flag: '🌐' },
    { code: 'DJF', nameKey: 'currencies.djf', flag: '🇩🇯' },
    { code: 'GNF', nameKey: 'currencies.gnf', flag: '🇬🇳' },
    { code: 'KMF', nameKey: 'currencies.kmf', flag: '🇰🇲' },
    { code: 'CDF', nameKey: 'currencies.cdf', flag: '🇨🇩' },
    { code: 'RWF', nameKey: 'currencies.rwf', flag: '🇷🇼' },
    { code: 'EGP', nameKey: 'currencies.egp', flag: '🇪🇬' },
    { code: 'GIP', nameKey: 'currencies.gip', flag: '🇬🇮' },
    { code: 'LBP', nameKey: 'currencies.lbp', flag: '🇱🇧' },
    { code: 'SSP', nameKey: 'currencies.ssp', flag: '🇸🇸' },
    { code: 'SDG', nameKey: 'currencies.sdg', flag: '🇸🇩' },
    { code: 'SYP', nameKey: 'currencies.syp', flag: '🇸🇾' },
    { code: 'GHS', nameKey: 'currencies.ghs', flag: '🇬🇭' },
    { code: 'HTG', nameKey: 'currencies.htg', flag: '🇭🇹' },
    { code: 'PYG', nameKey: 'currencies.pyg', flag: '🇵🇾' },
    { code: 'XCG', nameKey: 'currencies.xcg', flag: '🌐' },
    { code: 'PGK', nameKey: 'currencies.pgk', flag: '🇵🇬' },
    { code: 'LAK', nameKey: 'currencies.lak', flag: '🇱🇦' },
    { code: 'MWK', nameKey: 'currencies.mwk', flag: '🇲🇼' },
    { code: 'ZMW', nameKey: 'currencies.zmw', flag: '🇿🇲' },
    { code: 'AOA', nameKey: 'currencies.aoa', flag: '🇦🇴' },
    { code: 'MMK', nameKey: 'currencies.mmk', flag: '🇲🇲' },
    { code: 'GEL', nameKey: 'currencies.gel', flag: '🇬🇪' },
    { code: 'MDL', nameKey: 'currencies.mdl', flag: '🇲🇩' },
    { code: 'ALL', nameKey: 'currencies.all', flag: '🇦🇱' },
    { code: 'HNL', nameKey: 'currencies.hnl', flag: '🇭🇳' },
    { code: 'SLE', nameKey: 'currencies.sle', flag: '🇸🇱' },
    { code: 'SZL', nameKey: 'currencies.szl', flag: '🇸🇿' },
    { code: 'LSL', nameKey: 'currencies.lsl', flag: '🇱🇸' },
    { code: 'AZN', nameKey: 'currencies.azn', flag: '🇦🇿' },
    { code: 'MZN', nameKey: 'currencies.mzn', flag: '🇲🇿' },
    { code: 'NGN', nameKey: 'currencies.ngn', flag: '🇳🇬' },
    { code: 'ERN', nameKey: 'currencies.ern', flag: '🇪🇷' },
    { code: 'TWD', nameKey: 'currencies.twd', flag: '🇹🇼' },
    { code: 'TMT', nameKey: 'currencies.tmt', flag: '🇹🇲' },
    { code: 'MRU', nameKey: 'currencies.mru', flag: '🇲🇷' },
    { code: 'TOP', nameKey: 'currencies.top', flag: '🇹🇴' },
    { code: 'MOP', nameKey: 'currencies.mop', flag: '🇲🇴' },
    { code: 'ARS', nameKey: 'currencies.ars', flag: '🇦🇷' },
    { code: 'DOP', nameKey: 'currencies.dop', flag: '🇩🇴' },
    { code: 'COP', nameKey: 'currencies.cop', flag: '🇨🇴' },
    { code: 'CUP', nameKey: 'currencies.cup', flag: '🇨🇺' },
    { code: 'UYU', nameKey: 'currencies.uyu', flag: '🇺🇾' },
    { code: 'BWP', nameKey: 'currencies.bwp', flag: '🇧🇼' },
    { code: 'GTQ', nameKey: 'currencies.gtq', flag: '🇬🇹' },
    { code: 'IRR', nameKey: 'currencies.irr', flag: '🇮🇷' },
    { code: 'YER', nameKey: 'currencies.yer', flag: '🇾🇪' },
    { code: 'QAR', nameKey: 'currencies.qar', flag: '🇶🇦' },
    { code: 'OMR', nameKey: 'currencies.omr', flag: '🇴🇲' },
    { code: 'SAR', nameKey: 'currencies.sar', flag: '🇸🇦' },
    { code: 'KHR', nameKey: 'currencies.khr', flag: '🇰🇭' },
    { code: 'BYN', nameKey: 'currencies.byn', flag: '🇧🇾' },
    { code: 'RUB', nameKey: 'currencies.rub', flag: '🇷🇺' },
    { code: 'LKR', nameKey: 'currencies.lkr', flag: '🇱🇰' },
    { code: 'MVR', nameKey: 'currencies.mvr', flag: '🇲🇻' },
    { code: 'MUR', nameKey: 'currencies.mur', flag: '🇲🇺' },
    { code: 'NPR', nameKey: 'currencies.npr', flag: '🇳🇵' },
    { code: 'PKR', nameKey: 'currencies.pkr', flag: '🇵🇰' },
    { code: 'SCR', nameKey: 'currencies.scr', flag: '🇸🇨' },
    { code: 'PEN', nameKey: 'currencies.pen', flag: '🇵🇪' },
    { code: 'KGS', nameKey: 'currencies.kgs', flag: '🇰🇬' },
    { code: 'TJS', nameKey: 'currencies.tjs', flag: '🇹🇯' },
    { code: 'UZS', nameKey: 'currencies.uzs', flag: '🇺🇿' },
    { code: 'KES', nameKey: 'currencies.kes', flag: '🇰🇪' },
    { code: 'SOS', nameKey: 'currencies.sos', flag: '🇸🇴' },
    { code: 'TZS', nameKey: 'currencies.tzs', flag: '🇹🇿' },
    { code: 'UGX', nameKey: 'currencies.ugx', flag: '🇺🇬' },
    { code: 'BDT', nameKey: 'currencies.bdt', flag: '🇧🇩' },
    { code: 'WST', nameKey: 'currencies.wst', flag: '🇼🇸' },
    { code: 'KZT', nameKey: 'currencies.kzt', flag: '🇰🇿' },
    { code: 'MNT', nameKey: 'currencies.mnt', flag: '🇲🇳' },
    { code: 'VUV', nameKey: 'currencies.vuv', flag: '🇻🇺' },
    { code: 'BAM', nameKey: 'currencies.bam', flag: '🇧🇦' },
    { code: 'ZWG', nameKey: 'currencies.zwg', flag: '🇿🇼' },
];

export const currencyFlagMap: { [key: string]: string } = SUPPORTED_CURRENCIES.reduce((acc, currency) => {
    acc[currency.code] = currency.flag;
    return acc;
}, {} as { [key: string]: string });

/**
 * Funkcja pomocnicza do pobierania flagi z fallbackiem.
 * @param code - Kod waluty (np. "USD")
 * @returns np. "🇺🇸" lub "🌐" jeśli nie znaleziono.
 */
export const getCurrencyFlag = (code: string | undefined | null): string => {
    if (!code) return '🌐';
    return currencyFlagMap[code] || '🌐';
};
